package com.mkyong.customer.model;

// default package
// Generated 10/Out/2014 16:01:08 by Hibernate Tools 3.6.0

/**
 * HighlevelInformation generated by hbm2java
 */
public class HighlevelInformation {

	private Integer idHighlevelInformation;
	private String description;
	private int dataContextIdDataContext;

	public HighlevelInformation() {
	}

	public HighlevelInformation(int dataContextIdDataContext) {
		this.dataContextIdDataContext = dataContextIdDataContext;
	}

	public HighlevelInformation(String description, int dataContextIdDataContext) {
		this.description = description;
		this.dataContextIdDataContext = dataContextIdDataContext;
	}

	public Integer getIdHighlevelInformation() {
		return this.idHighlevelInformation;
	}

	public void setIdHighlevelInformation(Integer idHighlevelInformation) {
		this.idHighlevelInformation = idHighlevelInformation;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getDataContextIdDataContext() {
		return this.dataContextIdDataContext;
	}

	public void setDataContextIdDataContext(int dataContextIdDataContext) {
		this.dataContextIdDataContext = dataContextIdDataContext;
	}

}
