package com.mkyong.customer.model;

// default package
// Generated 10/Out/2014 16:01:08 by Hibernate Tools 3.6.0

/**
 * ModalitiesHasSensorId generated by hbm2java
 */
public class ModalitiesHasSensorId {

	private int modalitiesIdModalities;
	private int sensorIdSensor;

	public ModalitiesHasSensorId() {
	}

	public ModalitiesHasSensorId(int modalitiesIdModalities, int sensorIdSensor) {
		this.modalitiesIdModalities = modalitiesIdModalities;
		this.sensorIdSensor = sensorIdSensor;
	}

	public int getModalitiesIdModalities() {
		return this.modalitiesIdModalities;
	}

	public void setModalitiesIdModalities(int modalitiesIdModalities) {
		this.modalitiesIdModalities = modalitiesIdModalities;
	}

	public int getSensorIdSensor() {
		return this.sensorIdSensor;
	}

	public void setSensorIdSensor(int sensorIdSensor) {
		this.sensorIdSensor = sensorIdSensor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModalitiesHasSensorId))
			return false;
		ModalitiesHasSensorId castOther = (ModalitiesHasSensorId) other;

		return (this.getModalitiesIdModalities() == castOther
				.getModalitiesIdModalities())
				&& (this.getSensorIdSensor() == castOther.getSensorIdSensor());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getModalitiesIdModalities();
		result = 37 * result + this.getSensorIdSensor();
		return result;
	}

}
