package com.mkyong.customer.model;

// default package
// Generated 10/Out/2014 16:01:08 by Hibernate Tools 3.6.0

/**
 * Modalities generated by hbm2java
 */
public class Modalities {

	private Integer idModalities;
	private String description;

	public Modalities() {
	}

	public Modalities(String description) {
		this.description = description;
	}

	public Integer getIdModalities() {
		return this.idModalities;
	}

	public void setIdModalities(Integer idModalities) {
		this.idModalities = idModalities;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
