package com.mkyong.customer.model;

// default package
// Generated 10/Out/2014 16:01:08 by Hibernate Tools 3.6.0

/**
 * ModalitiesHasSensor generated by hbm2java
 */
public class ModalitiesHasSensor {

	private ModalitiesHasSensorId id;

	public ModalitiesHasSensor() {
	}

	public ModalitiesHasSensor(ModalitiesHasSensorId id) {
		this.id = id;
	}

	public ModalitiesHasSensorId getId() {
		return this.id;
	}

	public void setId(ModalitiesHasSensorId id) {
		this.id = id;
	}

}
