package com.mkyong.customer.model;

// default package
// Generated 10/Out/2014 16:01:08 by Hibernate Tools 3.6.0

/**
 * Real generated by hbm2java
 */
public class Real {

	private Integer idReal;
	private String description;
	private String timeCreation;
	private int dataContextIdDataContext;

	public Real() {
	}

	public Real(int dataContextIdDataContext) {
		this.dataContextIdDataContext = dataContextIdDataContext;
	}

	public Real(String description, String timeCreation,
			int dataContextIdDataContext) {
		this.description = description;
		this.timeCreation = timeCreation;
		this.dataContextIdDataContext = dataContextIdDataContext;
	}

	public Integer getIdReal() {
		return this.idReal;
	}

	public void setIdReal(Integer idReal) {
		this.idReal = idReal;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getTimeCreation() {
		return this.timeCreation;
	}

	public void setTimeCreation(String timeCreation) {
		this.timeCreation = timeCreation;
	}

	public int getDataContextIdDataContext() {
		return this.dataContextIdDataContext;
	}

	public void setDataContextIdDataContext(int dataContextIdDataContext) {
		this.dataContextIdDataContext = dataContextIdDataContext;
	}

}
