package com.mkyong.customer.model;

// default package
// Generated 10/Out/2014 16:01:08 by Hibernate Tools 3.6.0

/**
 * SensorNode generated by hbm2java
 */
public class SensorNode {

	private Integer idSensorNode;
	private String description;
	private String address;
	private int sensorIdSensor;

	public SensorNode() {
	}

	public SensorNode(int sensorIdSensor) {
		this.sensorIdSensor = sensorIdSensor;
	}

	public SensorNode(String description, String address, int sensorIdSensor) {
		this.description = description;
		this.address = address;
		this.sensorIdSensor = sensorIdSensor;
	}

	public Integer getIdSensorNode() {
		return this.idSensorNode;
	}

	public void setIdSensorNode(Integer idSensorNode) {
		this.idSensorNode = idSensorNode;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public int getSensorIdSensor() {
		return this.sensorIdSensor;
	}

	public void setSensorIdSensor(int sensorIdSensor) {
		this.sensorIdSensor = sensorIdSensor;
	}

}
