package com.mkyong.customer.model;

// default package
// Generated 10/Out/2014 16:01:08 by Hibernate Tools 3.6.0

/**
 * Sensor generated by hbm2java
 */
public class Sensor {

	private Integer idSensor;
	private String dataPeriodicity;
	private String type;
	private String location;
	private String sensorIdentifier;

	public Sensor() {
	}

	public Sensor(String sensorIdentifier) {
		this.sensorIdentifier = sensorIdentifier;
	}

	public Sensor(String dataPeriodicity, String type, String location,
			String sensorIdentifier) {
		this.dataPeriodicity = dataPeriodicity;
		this.type = type;
		this.location = location;
		this.sensorIdentifier = sensorIdentifier;
	}

	public Integer getIdSensor() {
		return this.idSensor;
	}

	public void setIdSensor(Integer idSensor) {
		this.idSensor = idSensor;
	}

	public String getDataPeriodicity() {
		return this.dataPeriodicity;
	}

	public void setDataPeriodicity(String dataPeriodicity) {
		this.dataPeriodicity = dataPeriodicity;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getSensorIdentifier() {
		return this.sensorIdentifier;
	}

	public void setSensorIdentifier(String sensorIdentifier) {
		this.sensorIdentifier = sensorIdentifier;
	}

}
