package com.mkyong.customer.model;

// default package
// Generated 10/Out/2014 16:01:08 by Hibernate Tools 3.6.0

/**
 * SensingData generated by hbm2java
 */
public class SensingData {

	private SensingDataId id;
	private String timeCreation;
	private String description;
	private String resourceAddress;
	private int classificationTagsIdClassificationTags;
	private int transformationLevelIdTransformationLevel;
	private int userProfileIdUserProfile;
	private int dataContextIdDataContext;
	private String timeEnd;

	public SensingData() {
	}

	public SensingData(SensingDataId id,
			int classificationTagsIdClassificationTags,
			int transformationLevelIdTransformationLevel,
			int userProfileIdUserProfile, int dataContextIdDataContext) {
		this.id = id;
		this.classificationTagsIdClassificationTags = classificationTagsIdClassificationTags;
		this.transformationLevelIdTransformationLevel = transformationLevelIdTransformationLevel;
		this.userProfileIdUserProfile = userProfileIdUserProfile;
		this.dataContextIdDataContext = dataContextIdDataContext;
	}

	public SensingData(SensingDataId id, String timeCreation,
			String description, String resourceAddress,
			int classificationTagsIdClassificationTags,
			int transformationLevelIdTransformationLevel,
			int userProfileIdUserProfile, int dataContextIdDataContext,
			String timeEnd) {
		this.id = id;
		this.timeCreation = timeCreation;
		this.description = description;
		this.resourceAddress = resourceAddress;
		this.classificationTagsIdClassificationTags = classificationTagsIdClassificationTags;
		this.transformationLevelIdTransformationLevel = transformationLevelIdTransformationLevel;
		this.userProfileIdUserProfile = userProfileIdUserProfile;
		this.dataContextIdDataContext = dataContextIdDataContext;
		this.timeEnd = timeEnd;
	}

	public SensingDataId getId() {
		return this.id;
	}

	public void setId(SensingDataId id) {
		this.id = id;
	}

	public String getTimeCreation() {
		return this.timeCreation;
	}

	public void setTimeCreation(String timeCreation) {
		this.timeCreation = timeCreation;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getResourceAddress() {
		return this.resourceAddress;
	}

	public void setResourceAddress(String resourceAddress) {
		this.resourceAddress = resourceAddress;
	}

	public int getClassificationTagsIdClassificationTags() {
		return this.classificationTagsIdClassificationTags;
	}

	public void setClassificationTagsIdClassificationTags(
			int classificationTagsIdClassificationTags) {
		this.classificationTagsIdClassificationTags = classificationTagsIdClassificationTags;
	}

	public int getTransformationLevelIdTransformationLevel() {
		return this.transformationLevelIdTransformationLevel;
	}

	public void setTransformationLevelIdTransformationLevel(
			int transformationLevelIdTransformationLevel) {
		this.transformationLevelIdTransformationLevel = transformationLevelIdTransformationLevel;
	}

	public int getUserProfileIdUserProfile() {
		return this.userProfileIdUserProfile;
	}

	public void setUserProfileIdUserProfile(int userProfileIdUserProfile) {
		this.userProfileIdUserProfile = userProfileIdUserProfile;
	}

	public int getDataContextIdDataContext() {
		return this.dataContextIdDataContext;
	}

	public void setDataContextIdDataContext(int dataContextIdDataContext) {
		this.dataContextIdDataContext = dataContextIdDataContext;
	}

	public String getTimeEnd() {
		return this.timeEnd;
	}

	public void setTimeEnd(String timeEnd) {
		this.timeEnd = timeEnd;
	}

}
