package com.mkyong.customer.model;

// default package
// Generated 10/Out/2014 16:01:08 by Hibernate Tools 3.6.0

/**
 * Study generated by hbm2java
 */
public class Study {

	private Integer idStudy;
	private String description;
	private String context;
	private String elements;
	private String timeCreation;
	private int dataContextIdDataContext;

	public Study() {
	}

	public Study(int dataContextIdDataContext) {
		this.dataContextIdDataContext = dataContextIdDataContext;
	}

	public Study(String description, String context, String elements,
			String timeCreation, int dataContextIdDataContext) {
		this.description = description;
		this.context = context;
		this.elements = elements;
		this.timeCreation = timeCreation;
		this.dataContextIdDataContext = dataContextIdDataContext;
	}

	public Integer getIdStudy() {
		return this.idStudy;
	}

	public void setIdStudy(Integer idStudy) {
		this.idStudy = idStudy;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getContext() {
		return this.context;
	}

	public void setContext(String context) {
		this.context = context;
	}

	public String getElements() {
		return this.elements;
	}

	public void setElements(String elements) {
		this.elements = elements;
	}

	public String getTimeCreation() {
		return this.timeCreation;
	}

	public void setTimeCreation(String timeCreation) {
		this.timeCreation = timeCreation;
	}

	public int getDataContextIdDataContext() {
		return this.dataContextIdDataContext;
	}

	public void setDataContextIdDataContext(int dataContextIdDataContext) {
		this.dataContextIdDataContext = dataContextIdDataContext;
	}

}
