package com.mkyong.customer.model;

// default package
// Generated 10/Out/2014 16:01:08 by Hibernate Tools 3.6.0

/**
 * Transformation generated by hbm2java
 */
public class Transformation {

	private Integer idTransformation;
	private String description;
	private int transformationLevelIdTransformationLevel;

	public Transformation() {
	}

	public Transformation(int transformationLevelIdTransformationLevel) {
		this.transformationLevelIdTransformationLevel = transformationLevelIdTransformationLevel;
	}

	public Transformation(String description,
			int transformationLevelIdTransformationLevel) {
		this.description = description;
		this.transformationLevelIdTransformationLevel = transformationLevelIdTransformationLevel;
	}

	public Integer getIdTransformation() {
		return this.idTransformation;
	}

	public void setIdTransformation(Integer idTransformation) {
		this.idTransformation = idTransformation;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getTransformationLevelIdTransformationLevel() {
		return this.transformationLevelIdTransformationLevel;
	}

	public void setTransformationLevelIdTransformationLevel(
			int transformationLevelIdTransformationLevel) {
		this.transformationLevelIdTransformationLevel = transformationLevelIdTransformationLevel;
	}

}
