package com.mkyong.customer.model;

// default package
// Generated 10/Out/2014 16:01:08 by Hibernate Tools 3.6.0

/**
 * UserProfile generated by hbm2java
 */
public class UserProfile {

	private Integer idUserProfile;
	private String username;
	private String password;

	public UserProfile() {
	}

	public UserProfile(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public Integer getIdUserProfile() {
		return this.idUserProfile;
	}

	public void setIdUserProfile(Integer idUserProfile) {
		this.idUserProfile = idUserProfile;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
