package com.mkyong.customer.model;

// default package
// Generated 10/Out/2014 16:01:08 by Hibernate Tools 3.6.0

/**
 * ValueUnits generated by hbm2java
 */
public class ValueUnits {

	private Integer idvalueUnits;
	private String description;
	private String symbol;
	private int sensingDataValueIdSensingDataValue;

	public ValueUnits() {
	}

	public ValueUnits(int sensingDataValueIdSensingDataValue) {
		this.sensingDataValueIdSensingDataValue = sensingDataValueIdSensingDataValue;
	}

	public ValueUnits(String description, String symbol,
			int sensingDataValueIdSensingDataValue) {
		this.description = description;
		this.symbol = symbol;
		this.sensingDataValueIdSensingDataValue = sensingDataValueIdSensingDataValue;
	}

	public Integer getIdvalueUnits() {
		return this.idvalueUnits;
	}

	public void setIdvalueUnits(Integer idvalueUnits) {
		this.idvalueUnits = idvalueUnits;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	public int getSensingDataValueIdSensingDataValue() {
		return this.sensingDataValueIdSensingDataValue;
	}

	public void setSensingDataValueIdSensingDataValue(
			int sensingDataValueIdSensingDataValue) {
		this.sensingDataValueIdSensingDataValue = sensingDataValueIdSensingDataValue;
	}

}
